language: rust
sudo: false

env:
  global:
    - secure: fX5PmUwA5RYQc9cabHVVAEmrBWLshOCAoAEnMrWVEjWkVZfOss80IEYbqMDEdCnVGmeVD4qv3YUuxPBW/hyEfuz2MrR5ab5iU/BREgnaRe19v1lZfVnXYcf8NUWyqMpUmD0YKo3EbNNfj4A+4aVQYmxqJSQqeT0HM3WTF3CTxR0=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
