language: rust
sudo: false

env:
  global:
    - secure: HyJiImHT9+sS3s00AxSkDVzL/up7w+6wGZbpPoIomFWMyOygxYPyuT2bWcgd9w86aa6TlX2C9oejiLaQuQLs3uXcbbf6FgV7ycoYtPbqpu7jO99VrUdVKCRO3b0ezUlnuA9BoB7B+CWzU2lJAmv+0WmvqnFWbYSv8XFBY+9kJk8=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
